# Generated by Django 4.2.10 on 2024-02-26 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "flight_number",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("departure_date", models.DateField()),
                ("departure_time", models.TimeField()),
                ("seat_count", models.PositiveIntegerField(default=60)),
                ("booked_seats", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
