# Generated by Django 4.2.10 on 2024-02-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_flight_seats_left"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="seats_left",
            field=models.IntegerField(default=60),
        ),
    ]
