# Generated by Django 4.2.10 on 2024-02-28 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_seat_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bookings.flight"
            ),
        ),
    ]
